steps:
- name: 'docker build: silo'
  args: ['build', '-t', 'gcr.io/cart-236115/silo:$COMMIT_SHA', '-f', 'silo.dockerfile', '.']
- name: 'docker build: webapi'
  args: ['build', '-t', 'gcr.io/cart-236115/webapi:$COMMIT_SHA', '-f', 'webapi.dockerfile', '.']
- name: 'docker build: client'
  args: ['build', '-t', 'gcr.io/cart-236115/client:$COMMIT_SHA', '-f', 'client.dockerfile', '.']
- name: 'docker push: silo'
  args: ['push', 'gcr.io/cart-236115/silo:$COMMIT_SHA']
- name: 'docker push: webapi'
  args: ['push', 'gcr.io/cart-236115/webapi:$COMMIT_SHA']
- name: 'docker push: client'
  args: ['push', 'gcr.io/cart-236115/client:$COMMIT_SHA']
images: ['gcr.io/cart-236115/silo', 'gcr.io/cart-236115/webapi', 'gcr.io/cart-236115/client']
