version: '3'
services:
  consul:
    image: consul:latest

  silo:
    build:
      dockerfile: Dockerfile
      context: output/silo/
    depends_on:
      - consul
  
  webapi:
    build:
      dockerfile: Dockerfile
      context: output/webapi
    ports:
      - "5000:80"
    depends_on:
      - silo
